<!DOCTYPE html>
<html>
    <head>        
        <?php include ('header.phtml'); ?>
    </head>

    <body>        
        <div class="container">

            <?php  include ('nav.phtml'); /*  navigation */    ?>
            
            <?php echo $this->layout()->content; ?>
            
            <hr>
            <?php include ('footer.phtml'); ?>
        </div> <!-- /container -->
       </body>
</html>