<style>
	table td {
		border: 1px solid black;
	}
</style>
<?php 
	
	if (!empty($this->message)) {
		print_r($this->message);				
	}

	?>

<p>
	<a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'add'));?>">Add new user</a>
	
</p>

<table>
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>Action</th>
	</tr>
	
	<?php foreach($this->users as $user) : ?>
	
	<tr>
		<!-- By default, the escape() method uses the PHP htmlspecialchars() function for escaping -->
		<!-- By default, the escape() method uses the PHP htmlspecialchars() function for escaping -->

		<td><?php echo $this->escape($user['username']);?></td>		
		<td>
<a href="<?php echo $this->url(
								array('controller'=>'user', 'action'=>'edit', 'id'=>$user['id']));?>"> Edit </a> &nbsp;
<a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'delete', 'id'=>$user['id']));?>"> Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>
